const punycode = require("punycode");
const biz1 = require("./hostname/Biz");
const cn1 = require("./hostname/Cn");
const jp1 = require("./hostname/Jp");
const com1 = require("./hostname/Com");

const validTlds = [
    "aaa",
    "aarp",
    "abarth",
    "abb",
    "abbott",
    "abbvie",
    "abc",
    "able",
    "abogado",
    "abudhabi",
    "ac",
    "academy",
    "accenture",
    "accountant",
    "accountants",
    "aco",
    "active",
    "actor",
    "ad",
    "adac",
    "ads",
    "adult",
    "ae",
    "aeg",
    "aero",
    "aetna",
    "af",
    "afamilycompany",
    "afl",
    "ag",
    "agakhan",
    "agency",
    "ai",
    "aig",
    "aigo",
    "airbus",
    "airforce",
    "airtel",
    "akdn",
    "al",
    "alfaromeo",
    "alibaba",
    "alipay",
    "allfinanz",
    "allstate",
    "ally",
    "alsace",
    "alstom",
    "am",
    "americanexpress",
    "americanfamily",
    "amex",
    "amfam",
    "amica",
    "amsterdam",
    "analytics",
    "android",
    "anquan",
    "anz",
    "ao",
    "aol",
    "apartments",
    "app",
    "apple",
    "aq",
    "aquarelle",
    "ar",
    "aramco",
    "archi",
    "army",
    "arpa",
    "art",
    "arte",
    "as",
    "asda",
    "asia",
    "associates",
    "at",
    "athleta",
    "attorney",
    "au",
    "auction",
    "audi",
    "audible",
    "audio",
    "auspost",
    "author",
    "auto",
    "autos",
    "avianca",
    "aw",
    "aws",
    "ax",
    "axa",
    "az",
    "azure",
    "ba",
    "baby",
    "baidu",
    "banamex",
    "bananarepublic",
    "band",
    "bank",
    "bar",
    "barcelona",
    "barclaycard",
    "barclays",
    "barefoot",
    "bargains",
    "baseball",
    "basketball",
    "bauhaus",
    "bayern",
    "bb",
    "bbc",
    "bbt",
    "bbva",
    "bcg",
    "bcn",
    "bd",
    "be",
    "beats",
    "beauty",
    "beer",
    "bentley",
    "berlin",
    "best",
    "bestbuy",
    "bet",
    "bf",
    "bg",
    "bh",
    "bharti",
    "bi",
    "bible",
    "bid",
    "bike",
    "bing",
    "bingo",
    "bio",
    "biz",
    "bj",
    "black",
    "blackfriday",
    "blanco",
    "blockbuster",
    "blog",
    "bloomberg",
    "blue",
    "bm",
    "bms",
    "bmw",
    "bn",
    "bnl",
    "bnpparibas",
    "bo",
    "boats",
    "boehringer",
    "bofa",
    "bom",
    "bond",
    "boo",
    "book",
    "booking",
    "boots",
    "bosch",
    "bostik",
    "boston",
    "bot",
    "boutique",
    "box",
    "br",
    "bradesco",
    "bridgestone",
    "broadway",
    "broker",
    "brother",
    "brussels",
    "bs",
    "bt",
    "budapest",
    "bugatti",
    "build",
    "builders",
    "business",
    "buy",
    "buzz",
    "bv",
    "bw",
    "by",
    "bz",
    "bzh",
    "ca",
    "cab",
    "cafe",
    "cal",
    "call",
    "calvinklein",
    "cam",
    "camera",
    "camp",
    "cancerresearch",
    "canon",
    "capetown",
    "capital",
    "capitalone",
    "car",
    "caravan",
    "cards",
    "care",
    "career",
    "careers",
    "cars",
    "cartier",
    "casa",
    "case",
    "caseih",
    "cash",
    "casino",
    "cat",
    "catering",
    "catholic",
    "cba",
    "cbn",
    "cbre",
    "cbs",
    "cc",
    "cd",
    "ceb",
    "center",
    "ceo",
    "cern",
    "cf",
    "cfa",
    "cfd",
    "cg",
    "ch",
    "chanel",
    "channel",
    "chase",
    "chat",
    "cheap",
    "chintai",
    "chloe",
    "christmas",
    "chrome",
    "chrysler",
    "church",
    "ci",
    "cipriani",
    "circle",
    "cisco",
    "citadel",
    "citi",
    "citic",
    "city",
    "cityeats",
    "ck",
    "cl",
    "claims",
    "cleaning",
    "click",
    "clinic",
    "clinique",
    "clothing",
    "cloud",
    "club",
    "clubmed",
    "cm",
    "cn",
    "co",
    "coach",
    "codes",
    "coffee",
    "college",
    "cologne",
    "com",
    "comcast",
    "commbank",
    "community",
    "company",
    "compare",
    "computer",
    "comsec",
    "condos",
    "construction",
    "consulting",
    "contact",
    "contractors",
    "cooking",
    "cookingchannel",
    "cool",
    "coop",
    "corsica",
    "country",
    "coupon",
    "coupons",
    "courses",
    "cr",
    "credit",
    "creditcard",
    "creditunion",
    "cricket",
    "crown",
    "crs",
    "cruise",
    "cruises",
    "csc",
    "cu",
    "cuisinella",
    "cv",
    "cw",
    "cx",
    "cy",
    "cymru",
    "cyou",
    "cz",
    "dabur",
    "dad",
    "dance",
    "data",
    "date",
    "dating",
    "datsun",
    "day",
    "dclk",
    "dds",
    "de",
    "deal",
    "dealer",
    "deals",
    "degree",
    "delivery",
    "dell",
    "deloitte",
    "delta",
    "democrat",
    "dental",
    "dentist",
    "desi",
    "design",
    "dev",
    "dhl",
    "diamonds",
    "diet",
    "digital",
    "direct",
    "directory",
    "discount",
    "discover",
    "dish",
    "diy",
    "dj",
    "dk",
    "dm",
    "dnp",
    "do",
    "docs",
    "doctor",
    "dodge",
    "dog",
    "doha",
    "domains",
    "dot",
    "download",
    "drive",
    "dtv",
    "dubai",
    "duck",
    "dunlop",
    "duns",
    "dupont",
    "durban",
    "dvag",
    "dvr",
    "dz",
    "earth",
    "eat",
    "ec",
    "eco",
    "edeka",
    "edu",
    "education",
    "ee",
    "eg",
    "email",
    "emerck",
    "energy",
    "engineer",
    "engineering",
    "enterprises",
    "epost",
    "epson",
    "equipment",
    "er",
    "ericsson",
    "erni",
    "es",
    "esq",
    "estate",
    "esurance",
    "et",
    "eu",
    "eurovision",
    "eus",
    "events",
    "everbank",
    "exchange",
    "expert",
    "exposed",
    "express",
    "extraspace",
    "fage",
    "fail",
    "fairwinds",
    "faith",
    "family",
    "fan",
    "fans",
    "farm",
    "farmers",
    "fashion",
    "fast",
    "fedex",
    "feedback",
    "ferrari",
    "ferrero",
    "fi",
    "fiat",
    "fidelity",
    "fido",
    "film",
    "final",
    "finance",
    "financial",
    "fire",
    "firestone",
    "firmdale",
    "fish",
    "fishing",
    "fit",
    "fitness",
    "fj",
    "fk",
    "flickr",
    "flights",
    "flir",
    "florist",
    "flowers",
    "fly",
    "fm",
    "fo",
    "foo",
    "food",
    "foodnetwork",
    "football",
    "ford",
    "forex",
    "forsale",
    "forum",
    "foundation",
    "fox",
    "fr",
    "free",
    "fresenius",
    "frl",
    "frogans",
    "frontdoor",
    "frontier",
    "ftr",
    "fujitsu",
    "fujixerox",
    "fun",
    "fund",
    "furniture",
    "futbol",
    "fyi",
    "ga",
    "gal",
    "gallery",
    "gallo",
    "gallup",
    "game",
    "games",
    "gap",
    "garden",
    "gb",
    "gbiz",
    "gd",
    "gdn",
    "ge",
    "gea",
    "gent",
    "genting",
    "george",
    "gf",
    "gg",
    "ggee",
    "gh",
    "gi",
    "gift",
    "gifts",
    "gives",
    "giving",
    "gl",
    "glade",
    "glass",
    "gle",
    "global",
    "globo",
    "gm",
    "gmail",
    "gmbh",
    "gmo",
    "gmx",
    "gn",
    "godaddy",
    "gold",
    "goldpoint",
    "golf",
    "goo",
    "goodhands",
    "goodyear",
    "goog",
    "google",
    "gop",
    "got",
    "gov",
    "gp",
    "gq",
    "gr",
    "grainger",
    "graphics",
    "gratis",
    "green",
    "gripe",
    "group",
    "gs",
    "gt",
    "gu",
    "guardian",
    "gucci",
    "guge",
    "guide",
    "guitars",
    "guru",
    "gw",
    "gy",
    "hair",
    "hamburg",
    "hangout",
    "haus",
    "hbo",
    "hdfc",
    "hdfcbank",
    "health",
    "healthcare",
    "help",
    "helsinki",
    "here",
    "hermes",
    "hgtv",
    "hiphop",
    "hisamitsu",
    "hitachi",
    "hiv",
    "hk",
    "hkt",
    "hm",
    "hn",
    "hockey",
    "holdings",
    "holiday",
    "homedepot",
    "homegoods",
    "homes",
    "homesense",
    "honda",
    "honeywell",
    "horse",
    "hospital",
    "host",
    "hosting",
    "hot",
    "hoteles",
    "hotmail",
    "house",
    "how",
    "hr",
    "hsbc",
    "ht",
    "htc",
    "hu",
    "hughes",
    "hyatt",
    "hyundai",
    "ibm",
    "icbc",
    "ice",
    "icu",
    "id",
    "ie",
    "ieee",
    "ifm",
    "ikano",
    "il",
    "im",
    "imamat",
    "imdb",
    "immo",
    "immobilien",
    "in",
    "industries",
    "infiniti",
    "info",
    "ing",
    "ink",
    "institute",
    "insurance",
    "insure",
    "int",
    "intel",
    "international",
    "intuit",
    "investments",
    "io",
    "ipiranga",
    "iq",
    "ir",
    "irish",
    "is",
    "iselect",
    "ismaili",
    "ist",
    "istanbul",
    "it",
    "itau",
    "itv",
    "iveco",
    "iwc",
    "jaguar",
    "java",
    "jcb",
    "jcp",
    "je",
    "jeep",
    "jetzt",
    "jewelry",
    "jio",
    "jlc",
    "jll",
    "jm",
    "jmp",
    "jnj",
    "jo",
    "jobs",
    "joburg",
    "jot",
    "joy",
    "jp",
    "jpmorgan",
    "jprs",
    "juegos",
    "juniper",
    "kaufen",
    "kddi",
    "ke",
    "kerryhotels",
    "kerrylogistics",
    "kerryproperties",
    "kfh",
    "kg",
    "kh",
    "ki",
    "kia",
    "kim",
    "kinder",
    "kindle",
    "kitchen",
    "kiwi",
    "km",
    "kn",
    "koeln",
    "komatsu",
    "kosher",
    "kp",
    "kpmg",
    "kpn",
    "kr",
    "krd",
    "kred",
    "kuokgroup",
    "kw",
    "ky",
    "kyoto",
    "kz",
    "la",
    "lacaixa",
    "ladbrokes",
    "lamborghini",
    "lamer",
    "lancaster",
    "lancia",
    "lancome",
    "land",
    "landrover",
    "lanxess",
    "lasalle",
    "lat",
    "latino",
    "latrobe",
    "law",
    "lawyer",
    "lb",
    "lc",
    "lds",
    "lease",
    "leclerc",
    "lefrak",
    "legal",
    "lego",
    "lexus",
    "lgbt",
    "li",
    "liaison",
    "lidl",
    "life",
    "lifeinsurance",
    "lifestyle",
    "lighting",
    "like",
    "lilly",
    "limited",
    "limo",
    "lincoln",
    "linde",
    "link",
    "lipsy",
    "live",
    "living",
    "lixil",
    "lk",
    "loan",
    "loans",
    "locker",
    "locus",
    "loft",
    "lol",
    "london",
    "lotte",
    "lotto",
    "love",
    "lpl",
    "lplfinancial",
    "lr",
    "ls",
    "lt",
    "ltd",
    "ltda",
    "lu",
    "lundbeck",
    "lupin",
    "luxe",
    "luxury",
    "lv",
    "ly",
    "ma",
    "macys",
    "madrid",
    "maif",
    "maison",
    "makeup",
    "man",
    "management",
    "mango",
    "market",
    "marketing",
    "markets",
    "marriott",
    "marshalls",
    "maserati",
    "mattel",
    "mba",
    "mc",
    "mcd",
    "mcdonalds",
    "mckinsey",
    "md",
    "me",
    "med",
    "media",
    "meet",
    "melbourne",
    "meme",
    "memorial",
    "men",
    "menu",
    "meo",
    "metlife",
    "mg",
    "mh",
    "miami",
    "microsoft",
    "mil",
    "mini",
    "mint",
    "mit",
    "mitsubishi",
    "mk",
    "ml",
    "mlb",
    "mls",
    "mm",
    "mma",
    "mn",
    "mo",
    "mobi",
    "mobile",
    "mobily",
    "moda",
    "moe",
    "moi",
    "mom",
    "monash",
    "money",
    "monster",
    "montblanc",
    "mopar",
    "mormon",
    "mortgage",
    "moscow",
    "moto",
    "motorcycles",
    "mov",
    "movie",
    "movistar",
    "mp",
    "mq",
    "mr",
    "ms",
    "msd",
    "mt",
    "mtn",
    "mtpc",
    "mtr",
    "mu",
    "museum",
    "mutual",
    "mv",
    "mw",
    "mx",
    "my",
    "mz",
    "na",
    "nab",
    "nadex",
    "nagoya",
    "name",
    "nationwide",
    "natura",
    "navy",
    "nba",
    "nc",
    "ne",
    "nec",
    "net",
    "netbank",
    "netflix",
    "network",
    "neustar",
    "new",
    "newholland",
    "news",
    "next",
    "nextdirect",
    "nexus",
    "nf",
    "nfl",
    "ng",
    "ngo",
    "nhk",
    "ni",
    "nico",
    "nike",
    "nikon",
    "ninja",
    "nissan",
    "nissay",
    "nl",
    "no",
    "nokia",
    "northwesternmutual",
    "norton",
    "now",
    "nowruz",
    "nowtv",
    "np",
    "nr",
    "nra",
    "nrw",
    "ntt",
    "nu",
    "nyc",
    "nz",
    "obi",
    "observer",
    "off",
    "office",
    "okinawa",
    "olayan",
    "olayangroup",
    "oldnavy",
    "ollo",
    "om",
    "omega",
    "one",
    "ong",
    "onl",
    "online",
    "onyourside",
    "ooo",
    "open",
    "oracle",
    "orange",
    "org",
    "organic",
    "orientexpress",
    "origins",
    "osaka",
    "otsuka",
    "ott",
    "ovh",
    "pa",
    "page",
    "pamperedchef",
    "panasonic",
    "panerai",
    "paris",
    "pars",
    "partners",
    "parts",
    "party",
    "passagens",
    "pay",
    "pccw",
    "pe",
    "pet",
    "pf",
    "pfizer",
    "pg",
    "ph",
    "pharmacy",
    "philips",
    "phone",
    "photo",
    "photography",
    "photos",
    "physio",
    "piaget",
    "pics",
    "pictet",
    "pictures",
    "pid",
    "pin",
    "ping",
    "pink",
    "pioneer",
    "pizza",
    "pk",
    "pl",
    "place",
    "play",
    "playstation",
    "plumbing",
    "plus",
    "pm",
    "pn",
    "pnc",
    "pohl",
    "poker",
    "politie",
    "porn",
    "post",
    "pr",
    "pramerica",
    "praxi",
    "press",
    "prime",
    "pro",
    "prod",
    "productions",
    "prof",
    "progressive",
    "promo",
    "properties",
    "property",
    "protection",
    "pru",
    "prudential",
    "ps",
    "pt",
    "pub",
    "pw",
    "pwc",
    "py",
    "qa",
    "qpon",
    "quebec",
    "quest",
    "qvc",
    "racing",
    "radio",
    "raid",
    "re",
    "read",
    "realestate",
    "realtor",
    "realty",
    "recipes",
    "red",
    "redstone",
    "redumbrella",
    "rehab",
    "reise",
    "reisen",
    "reit",
    "reliance",
    "ren",
    "rent",
    "rentals",
    "repair",
    "report",
    "republican",
    "rest",
    "restaurant",
    "review",
    "reviews",
    "rexroth",
    "rich",
    "richardli",
    "ricoh",
    "rightathome",
    "ril",
    "rio",
    "rip",
    "rmit",
    "ro",
    "rocher",
    "rocks",
    "rodeo",
    "rogers",
    "room",
    "rs",
    "rsvp",
    "ru",
    "ruhr",
    "run",
    "rw",
    "rwe",
    "ryukyu",
    "sa",
    "saarland",
    "safe",
    "safety",
    "sakura",
    "sale",
    "salon",
    "samsclub",
    "samsung",
    "sandvik",
    "sandvikcoromant",
    "sanofi",
    "sap",
    "sapo",
    "sarl",
    "sas",
    "save",
    "saxo",
    "sb",
    "sbi",
    "sbs",
    "sc",
    "sca",
    "scb",
    "schaeffler",
    "schmidt",
    "scholarships",
    "school",
    "schule",
    "schwarz",
    "science",
    "scjohnson",
    "scor",
    "scot",
    "sd",
    "se",
    "seat",
    "secure",
    "security",
    "seek",
    "select",
    "sener",
    "services",
    "ses",
    "seven",
    "sew",
    "sex",
    "sexy",
    "sfr",
    "sg",
    "sh",
    "shangrila",
    "sharp",
    "shaw",
    "shell",
    "shia",
    "shiksha",
    "shoes",
    "shop",
    "shopping",
    "shouji",
    "show",
    "showtime",
    "shriram",
    "si",
    "silk",
    "sina",
    "singles",
    "site",
    "sj",
    "sk",
    "ski",
    "skin",
    "sky",
    "skype",
    "sl",
    "sling",
    "sm",
    "smart",
    "smile",
    "sn",
    "sncf",
    "so",
    "soccer",
    "social",
    "softbank",
    "software",
    "sohu",
    "solar",
    "solutions",
    "song",
    "sony",
    "soy",
    "space",
    "spiegel",
    "spot",
    "spreadbetting",
    "sr",
    "srl",
    "srt",
    "st",
    "stada",
    "staples",
    "star",
    "starhub",
    "statebank",
    "statefarm",
    "statoil",
    "stc",
    "stcgroup",
    "stockholm",
    "storage",
    "store",
    "stream",
    "studio",
    "study",
    "style",
    "su",
    "sucks",
    "supplies",
    "supply",
    "support",
    "surf",
    "surgery",
    "suzuki",
    "sv",
    "swatch",
    "swiftcover",
    "swiss",
    "sx",
    "sy",
    "sydney",
    "symantec",
    "systems",
    "sz",
    "tab",
    "taipei",
    "talk",
    "taobao",
    "target",
    "tatamotors",
    "tatar",
    "tattoo",
    "tax",
    "taxi",
    "tc",
    "tci",
    "td",
    "tdk",
    "team",
    "tech",
    "technology",
    "tel",
    "telecity",
    "telefonica",
    "temasek",
    "tennis",
    "teva",
    "tf",
    "tg",
    "th",
    "thd",
    "theater",
    "theatre",
    "tiaa",
    "tickets",
    "tienda",
    "tiffany",
    "tips",
    "tires",
    "tirol",
    "tj",
    "tjmaxx",
    "tjx",
    "tk",
    "tkmaxx",
    "tl",
    "tm",
    "tmall",
    "tn",
    "to",
    "today",
    "tokyo",
    "tools",
    "top",
    "toray",
    "toshiba",
    "total",
    "tours",
    "town",
    "toyota",
    "toys",
    "tr",
    "trade",
    "trading",
    "training",
    "travel",
    "travelchannel",
    "travelers",
    "travelersinsurance",
    "trust",
    "trv",
    "tt",
    "tube",
    "tui",
    "tunes",
    "tushu",
    "tv",
    "tvs",
    "tw",
    "tz",
    "ua",
    "ubank",
    "ubs",
    "uconnect",
    "ug",
    "uk",
    "unicom",
    "university",
    "uno",
    "uol",
    "ups",
    "us",
    "uy",
    "uz",
    "va",
    "vacations",
    "vana",
    "vanguard",
    "vc",
    "ve",
    "vegas",
    "ventures",
    "verisign",
    "versicherung",
    "vet",
    "vg",
    "vi",
    "viajes",
    "video",
    "vig",
    "viking",
    "villas",
    "vin",
    "vip",
    "virgin",
    "visa",
    "vision",
    "vista",
    "vistaprint",
    "viva",
    "vivo",
    "vlaanderen",
    "vn",
    "vodka",
    "volkswagen",
    "volvo",
    "vote",
    "voting",
    "voto",
    "voyage",
    "vu",
    "vuelos",
    "wales",
    "walmart",
    "walter",
    "wang",
    "wanggou",
    "warman",
    "watch",
    "watches",
    "weather",
    "weatherchannel",
    "webcam",
    "weber",
    "website",
    "wed",
    "wedding",
    "weibo",
    "weir",
    "wf",
    "whoswho",
    "wien",
    "wiki",
    "williamhill",
    "win",
    "windows",
    "wine",
    "winners",
    "wme",
    "wolterskluwer",
    "woodside",
    "work",
    "works",
    "world",
    "wow",
    "ws",
    "wtc",
    "wtf",
    "xbox",
    "xerox",
    "xfinity",
    "xihuan",
    "xin",
    "कॉम",
    "セール",
    "佛山",
    "慈善",
    "集团",
    "在线",
    "한국",
    "大众汽车",
    "点看",
    "คอม",
    "ভারত",
    "八卦",
    "موقع",
    "বাংলা",
    "公益",
    "公司",
    "香格里拉",
    "网站",
    "移动",
    "我爱你",
    "москва",
    "қаз",
    "католик",
    "онлайн",
    "сайт",
    "联通",
    "срб",
    "бг",
    "бел",
    "קום",
    "时尚",
    "微博",
    "淡马锡",
    "ファッション",
    "орг",
    "नेट",
    "ストア",
    "삼성",
    "சிங்கப்பூர்",
    "商标",
    "商店",
    "商城",
    "дети",
    "мкд",
    "ею",
    "ポイント",
    "新闻",
    "工行",
    "家電",
    "كوم",
    "中文网",
    "中信",
    "中国",
    "中國",
    "娱乐",
    "谷歌",
    "భారత్",
    "ලංකා",
    "電訊盈科",
    "购物",
    "クラウド",
    "ભારત",
    "通販",
    "भारत",
    "网店",
    "संगठन",
    "餐厅",
    "网络",
    "ком",
    "укр",
    "香港",
    "诺基亚",
    "食品",
    "飞利浦",
    "台湾",
    "台灣",
    "手表",
    "手机",
    "мон",
    "الجزائر",
    "عمان",
    "ارامكو",
    "ایران",
    "العليان",
    "امارات",
    "بازار",
    "الاردن",
    "موبايلي",
    "بھارت",
    "المغرب",
    "ابوظبي",
    "السعودية",
    "كاثوليك",
    "سودان",
    "همراه",
    "عراق",
    "مليسيا",
    "澳門",
    "닷컴",
    "政府",
    "شبكة",
    "بيتك",
    "გე",
    "机构",
    "组织机构",
    "健康",
    "ไทย",
    "سورية",
    "рус",
    "рф",
    "珠宝",
    "تونس",
    "大拿",
    "みんな",
    "グーグル",
    "ελ",
    "世界",
    "書籍",
    "ਭਾਰਤ",
    "网址",
    "닷넷",
    "コム",
    "天主教",
    "游戏",
    "vermögensberater",
    "vermögensberatung",
    "企业",
    "信息",
    "嘉里大酒店",
    "嘉里",
    "مصر",
    "قطر",
    "广东",
    "இலங்கை",
    "இந்தியா",
    "հայ",
    "新加坡",
    "فلسطين",
    "政务",
    "xperia",
    "xxx",
    "xyz",
    "yachts",
    "yahoo",
    "yamaxun",
    "yandex",
    "ye",
    "yodobashi",
    "yoga",
    "yokohama",
    "you",
    "youtube",
    "yt",
    "yun",
    "za",
    "zappos",
    "zara",
    "zero",
    "zip",
    "zippo",
    "zm",
    "zone",
    "zuerich",
    "zw",
];

const validIdns = {
    AC: [/^[\u002d0-9a-zà-öø-ÿāăąćĉċčďđēėęěĝġģĥħīįĵķĺļľŀłńņňŋőœŕŗřśŝşšţťŧūŭůűųŵŷźżž]{1,63}$/i],
    AR: [/^[\u002d0-9a-zà-ãç-êìíñ-õü]{1,63}$/i],
    AS: [/^[\u002d0-9a-zà-öø-ÿāăąćĉċčďđēĕėęěĝğġģĥħĩīĭįıĵķĸĺļľłńņňŋōŏőœŕŗřśŝşšţťŧũūŭůűųŵŷźż]{1,63}$/i],
    AT: [/^[\u002d0-9a-zà-öø-ÿœšž]{1,63}$/i],
    BIZ: biz1,
    BR: [/^[\u002d0-9a-zà-ãçéíó-õúü]{1,63}$/i],
    BV: [/^[\u002d0-9a-zàáä-éêñ-ôöøüčđńŋšŧž]{1,63}$/i],
    CAT: [/^[\u002d0-9a-z·àç-éíïòóúü]{1,63}$/i],
    CH: [/^[\u002d0-9a-zà-öø-ÿœ]{1,63}$/i],
    CL: [/^[\u002d0-9a-záéíñóúü]{1,63}$/i],
    CN: cn1,
    COM: com1,
    DE: ["/^[\u002d0-9a-zà-öø-ÿăąāćĉčċďđĕěėęēğĝġģĥħĭĩįīıĵķĺľļłńňņŋŏőōœĸŕřŗśŝšşťţŧŭůűũųūŵŷźžż]{1,63}$/i"],
    DK: [/^[\u002d0-9a-zäéöü]{1,63}$/i],
    EE: [/^[\u002d0-9a-zäõöüšž]{1,63}$/i],
    ES: [/^[\u002d0-9a-zàáçèéíïñòóúü·]{1,63}$/i],
    EU: [/^[\u002d0-9a-zà-öø-ÿ]{1,63}$/i,
        /^[\u002d0-9a-zāăąćĉċčďđēĕėęěĝğġģĥħĩīĭįıĵķĺļľŀłńņňŉŋōŏőœŕŗřśŝšťŧũūŭůűųŵŷźżž]{1,63}$/i,
        /^[\u002d0-9a-zșț]{1,63}$/i,
        /^[\u002d0-9a-zΐάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώ]{1,63}$/i,
        /^[\u002d0-9a-zабвгдежзийклмнопрстуфхцчшщъыьэюя]{1,63}$/i,
        /^[\u002d0-9a-zἀ-ἇἐ-ἕἠ-ἧἰ-ἷὀ-ὅὐ-ὗὠ-ὧὰ-ὼώᾀ-ᾇᾐ-ᾗᾠ-ᾧᾰ-ᾴᾶᾷῂῃῄῆῇῐ-ῒΐῖῗῠ-ῧῲῳῴῶῷ]{1,63}$/i],
    FI: [/^[\u002d0-9a-zäåö]{1,63}$/i],
    GR: [/^[\u002d0-9a-zΆΈΉΊΌΎ-ΡΣ-ώἀ-ἕἘ-Ἕἠ-ὅὈ-Ὅὐ-ὗὙὛὝὟ-ώᾀ-ᾴᾶ-ᾼῂῃῄῆ-ῌῐ-ΐῖ-Ίῠ-Ῥῲῳῴῶ-ῼ]{1,63}$/i],
    HK: cn1,
    HU: [/^[\u002d0-9a-záéíóöúüőű]{1,63}$/i],
    IL: [/^[\u002d0-9\u05D0-\u05EA]{1,63}$/i,
        /^[\u002d0-9a-z]{1,63}$/i],
    INFO: [/^[\u002d0-9a-zäåæéöøü]{1,63}$/i,
        /^[\u002d0-9a-záéíóöúüőű]{1,63}$/i,
        /^[\u002d0-9a-záæéíðóöúýþ]{1,63}$/i,
        /^[\uAC00-\uD7A3]{1,17}$/i,
        /^[\u002d0-9a-zāčēģīķļņōŗšūž]{1,63}$/i,
        /^[\u002d0-9a-ząčėęįšūųž]{1,63}$/i,
        /^[\u002d0-9a-zóąćęłńśźż]{1,63}$/i,
        /^[\u002d0-9a-záéíñóúü]{1,63}$/i],
    IO: [/^[\u002d0-9a-zà-öø-ÿăąāćĉčċďđĕěėęēğĝġģĥħĭĩįīıĵķĺľļłńňņŋŏőōœĸŕřŗśŝšşťţŧŭůűũųūŵŷźžż]{1,63}$/i],
    IS: [/^[\u002d0-9a-záéýúíóþæöð]{1,63}$/i],
    IT: [/^[\u002d0-9a-zàâäèéêëìîïòôöùûüæœçÿß-]{1,63}$/i],
    JP: jp1,
    KR: [/^[\uAC00-\uD7A3]{1,17}$/i],
    LI: [/^[\u002d0-9a-zà-öø-ÿœ]{1,63}$/i],
    LT: [/^[\u002d0-9ąčęėįšųūž]{1,63}$/i],
    MD: [/^[\u002d0-9ăâîşţ]{1,63}$/i],
    MUSEUM: [/^[\u002d0-9a-zà-öø-ÿāăąćċčďđēėęěğġģħīįıķĺļľłńņňŋōőœŕŗřśşšţťŧūůűųŵŷźżžǎǐǒǔ\u01E5\u01E7\u01E9\u01EFə\u0292ẁẃẅỳ]{1,63}$/i],
    NET: com1,
    NO: [/^[\u002d0-9a-zàáä-éêñ-ôöøüčđńŋšŧž]{1,63}$/i],
    NU: com1,
    ORG: [/^[\u002d0-9a-záéíñóúü]{1,63}$/i,
        /^[\u002d0-9a-zóąćęłńśźż]{1,63}$/i,
        /^[\u002d0-9a-záäåæéëíðóöøúüýþ]{1,63}$/i,
        /^[\u002d0-9a-záéíóöúüőű]{1,63}$/i,
        /^[\u002d0-9a-ząčėęįšūųž]{1,63}$/i,
        /^[\uAC00-\uD7A3]{1,17}$/i,
        /^[\u002d0-9a-zāčēģīķļņōŗšūž]{1,63}$/i],
    PE: [/^[\u002d0-9a-zñáéíóúü]{1,63}$/i],
    PL: [/^[\u002d0-9a-zāčēģīķļņōŗšūž]{1,63}$/i,
        /^[\u002dа-ик-ш\u0450ѓѕјљњќџ]{1,63}$/i,
        /^[\u002d0-9a-zâîăşţ]{1,63}$/i,
        /^[\u002d0-9а-яё\u04C2]{1,63}$/i,
        /^[\u002d0-9a-zàáâèéêìíîòóôùúûċġħż]{1,63}$/i,
        /^[\u002d0-9a-zàäåæéêòóôöøü]{1,63}$/i,
        /^[\u002d0-9a-zóąćęłńśźż]{1,63}$/i,
        /^[\u002d0-9a-zàáâãçéêíòóôõúü]{1,63}$/i,
        /^[\u002d0-9a-zâîăşţ]{1,63}$/i,
        /^[\u002d0-9a-záäéíóôúýčďĺľňŕšťž]{1,63}$/i,
        /^[\u002d0-9a-zçë]{1,63}$/i,
        /^[\u002d0-9а-ик-шђјљњћџ]{1,63}$/i,
        /^[\u002d0-9a-zćčđšž]{1,63}$/i,
        /^[\u002d0-9a-zâçöûüğış]{1,63}$/i,
        /^[\u002d0-9a-zäåæõöøüšž]{1,63}$/i,
        /^[\u002d0-9a-zàáçèéìíòóùú]{1,63}$/i,
        /^[\u002d0-9a-zàáéíóöúüőű]{1,63}$/i,
        /^[\u002d0-9ΐά-ώ]{1,63}$/i,
        /^[\u002d0-9a-zàáâåæçèéêëðóôöøüþœ]{1,63}$/i,
        /^[\u002d0-9a-záäéíóöúüýčďěňřšťůž]{1,63}$/i,
        /^[\u002d0-9a-z·àçèéíïòóúü]{1,63}$/i,
        /^[\u002d0-9а-ъьюя\u0450\u045D]{1,63}$/i,
        /^[\u002d0-9а-яёіў]{1,63}$/i,
        /^[\u002d0-9a-ząčėęįšūųž]{1,63}$/i,
        /^[\u002d0-9a-záäåæéëíðóöøúüýþ]{1,63}$/i,
        /^[\u002d0-9a-zàâæçèéêëîïñôùûüÿœ]{1,63}$/i,
        /^[\u002d0-9а-щъыьэюяёєіїґ]{1,63}$/i,
        /^[\u002d0-9a-zäõöüšž]{1,63}$/i,
        /^[\u002d0-9a-zĉĝĥĵŝŭ]{1,63}$/i,
        /^[\u002d0-9a-zâäéëîô]{1,63}$/i,
        /^[\u002d0-9a-zàáâäåæçèéêëìíîïðñòôöøùúûüýćčłńřśš]{1,63}$/i,
        /^[\u002d0-9א-ת]{1,63}$/i,
        /^[\u002d0-9a-záéíñóúü]{1,63}$/i],
    PR: [/^[\u002d0-9a-záéíóúñäëïüöâêîôûàèùæçœãõ]{1,63}$/i],
    PT: [/^[\u002d0-9a-záàâãçéêíóôõú]{1,63}$/i],
    RU: [/^[\u002d0-9а-яё]{1,63}$/i],
    SA: [/^[\u002d.0-9\u0621-\u063A\u0641-\u064A\u0660-\u0669]{1,63}$/i],
    SE: [/^[\u002d0-9a-zäåéöü]{1,63}$/i],
    SH: [/^[\u002d0-9a-zà-öø-ÿăąāćĉčċďđĕěėęēğĝġģĥħĭĩįīıĵķĺľļłńňņŋŏőōœĸŕřŗśŝšşťţŧŭůűũųūŵŷźžż]{1,63}$/i],
    SI: [/^[\u002d0-9a-zà-öø-ÿ]{1,63}$/i,
        /^[\u002d0-9a-zāăąćĉċčďđēĕėęěĝğġģĥħĩīĭįıĵķĺļľŀłńņňŉŋōŏőœŕŗřśŝšťŧũūŭůűųŵŷźżž]{1,63}$/i,
        /^[\u002d0-9a-zșț]{1,63}$/i],
    SJ: [/^[\u002d0-9a-zàáä-éêñ-ôöøüčđńŋšŧž]{1,63}$/i],
    TH: [/^[\u002d0-9a-z\u0E01-\u0E3A\u0E40-\u0E4D\u0E50-\u0E59]{1,63}$/i],
    TM: [/^[\u002d0-9a-zà-öø-ÿāăąćĉċčďđēėęěĝġģĥħīįĵķĺļľŀłńņňŋőœŕŗřśŝşšţťŧūŭůűųŵŷźżž]{1,63}$/i],
    TW: cn1,
    TR: [/^[\u002d0-9a-zğıüşöç]{1,63}$/i],
    UA: [/^[\u002d0-9a-zабвгдежзийклмнопрстуфхцчшщъыьэюяѐёђѓєѕіїјљњћќѝўџґӂʼ]{1,63}$/i],
    VE: [/^[\u002d0-9a-záéíóúüñ]{1,63}$/i],
    VN: [/^[ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝàáâãèéêìíòóôõùúýĂăĐđĨĩŨũƠơƯư\u1EA0-\u1EF9]{1,63}$/i],
    мон: [/^[\u002d0-9\u0430-\u044F]{1,63}$/i],
    срб: [/^[\u002d0-9а-ик-шђјљњћџ]{1,63}$/i],
    сайт: [/^[\u002d0-9а-яёіїѝйўґг]{1,63}$/i],
    онлайн: [/^[\u002d0-9а-яёіїѝйўґг]{1,63}$/i],
    中国: cn1,
    中國: cn1,
    ලංකා: [/^[\u0d80-\u0dff]{1,63}$/i],
    香港: cn1,
    台湾: cn1,
    台灣: cn1,
    امارات: [/^[\u0621-\u0624\u0626-\u063A\u0641\u0642\u0644-\u0648\u067E\u0686\u0698\u06A9\u06AF\u06CC\u06F0-\u06F9]{1,30}$/i],
    الاردن: [/^[\u0621-\u0624\u0626-\u063A\u0641\u0642\u0644-\u0648\u067E\u0686\u0698\u06A9\u06AF\u06CC\u06F0-\u06F9]{1,30}$/i],
    السعودية: [/^[\u0621-\u0624\u0626-\u063A\u0641\u0642\u0644-\u0648\u067E\u0686\u0698\u06A9\u06AF\u06CC\u06F0-\u06F9]{1,30}$/i],
    ไทย: [/^[\u002d0-9a-z\u0E01-\u0E3A\u0E40-\u0E4D\u0E50-\u0E59]{1,63}$/i],
    рф: [/^[\u002d0-9а-яё]{1,63}$/i],
    تونس: [/^[\u0621-\u0624\u0626-\u063A\u0641\u0642\u0644-\u0648\u067E\u0686\u0698\u06A9\u06AF\u06CC\u06F0-\u06F9]{1,30}$/i],
    مصر: [/^[\u0621-\u0624\u0626-\u063A\u0641\u0642\u0644-\u0648\u067E\u0686\u0698\u06A9\u06AF\u06CC\u06F0-\u06F9]{1,30}$/i],
    இலங்கை: [/^[\u0b80-\u0bff]{1,63}$/i],
    فلسطين: [/^[\u0621-\u0624\u0626-\u063A\u0641\u0642\u0644-\u0648\u067E\u0686\u0698\u06A9\u06AF\u06CC\u06F0-\u06F9]{1,30}$/i],
    شبكة: [/^[\u0621-\u0624\u0626-\u063A\u0641\u0642\u0644-\u0648\u067E\u0686\u0698\u06A9\u06AF\u06CC\u06F0-\u06F9]{1,30}$/i],
};

const idnLength = {
    BIZ: {
        5: 17,
        11: 15,
        12: 20,
    },
    CN: {
        1: 20,
    },
    COM: {
        3: 17,
        5: 20,
    },
    HK: {
        1: 15,
    },
    INFO: {
        4: 17,
    },
    KR: {
        1: 17,
    },
    NET: {
        3: 17,
        5: 20,
    },
    ORG: {
        6: 17,
    },
    TW: {
        1: 20,
    },
    امارات: {
        1: 30,
    },
    الاردن: {
        1: 30,
    },
    السعودية: {
        1: 30,
    },
    تونس: {
        1: 30,
    },
    مصر: {
        1: 30,
    },
    فلسطين: {
        1: 30,
    },
    شبكة: {
        1: 30,
    },
    中国: {
        1: 20,
    },
    中國: {
        1: 20,
    },
    香港: {
        1: 20,
    },
    台湾: {
        1: 20,
    },
    台灣: {
        1: 20,
    },
};

let isValid = function (value) {
    let status;

    if (typeof value !== "string") {
        return false;
    }

    if ((value.match(/^[0-9.]*$/) && value.indexOf(".") !== -1)
        || (value.match(/^[0-9a-f:.]*$/i) && value.indexOf(":") !== -1)) {
        return false;
    }

    let domainParts = value.split(".");

    if (domainParts.length > 1 && value.length >= 4 && value.length <= 254) {
        do {
            let globalBreak = false;

            let tld,
                lastDomainPart = domainParts[domainParts.length - 1];

            if (value.match(/([^.]{2,63})$/g) || (validIdns[lastDomainPart] != null)) {
                tld = value.match(/([^.]{2,63})$/g)[0];
                if (tld.indexOf("xn--") === 0) {
                    try {
                        tld = punycode.decode(tld.substr(4));
                    } catch (err) {
                        status = false;
                        break;
                    }
                } else {
                    tld = tld.toUpperCase();
                }

                if ((validTlds.indexOf(tld.toLowerCase()) === -1) && (validTlds.indexOf(tld) === -1)) {
                    status = false;
                    break;
                }
                domainParts.length--;

                let regexChars = [/^[a-z0-9]{1,63}$/i];
                if (validIdns[tld]) {
                    if (typeof validIdns[tld] === "function") {
                        regexChars = regexChars.concat(validIdns[tld]());
                    } else {
                        regexChars = regexChars.concat(validIdns[tld]);
                    }
                }

                let check = 0;

                for (let i = 0; i < domainParts.length; i++) {
                    let domainPart = domainParts[i];

                    if (domainPart.indexOf("xn--") === 0) {
                        try {
                            domainPart = punycode.decode(domainPart.substr(4));
                        } catch (err) {
                            status = false;
                            globalBreak = true;
                        }
                    }

                    if (domainPart.indexOf("-") === 0
                        || (domainPart.length > 2 && domainPart.indexOf("-", 2) === 2 && domainPart.indexOf("-", 3) === 3)
                        || (domainPart.indexOf("-") === (domainPart.length - 1))) {
                        status = false;
                        globalBreak = true;
                        break;
                    }

                    let checked = false;
                    for (let j = 0; j < regexChars.length; j++) {
                        let regexChar = typeof regexChars[j] === "string" ? RegExp(regexChars[j].slice(1, -2), "i") : regexChars[j];

                        status = regexChar.test(domainPart);
                        if (status) {
                            let length = 63;

                            if (idnLength[tld] && idnLength[tld][j + 1]) {
                                length = idnLength[tld][j + 1];
                            }

                            if (domainPart.length > length) {
                                status = false;
                            } else {
                                checked = true;
                                break;
                            }
                        }
                    }

                    if (checked) {
                        ++check;
                    }
                }

                if (globalBreak) {
                    break;
                }

                if (check !== domainParts.length) {
                    status = false;
                }
            } else {
                status = false;
            }
        } while (0);
        if (status) {
            return true;
        }
    }

    return false;
};

module.exports = {
    isValid
};



