module.exports = {
    INTERNAL_ERROR: "INTERNAL_ERROR",
    INCORRECT_DATA: "INCORRECT_DATA",
    NOT_REGISTERED: "NOT_REGISTERED",
    PASSWORDS_DONT_MATCH: "PASSWORDS_DONT_MATCH",
    EMAIL_NOT_UNIQUE:"EMAIL_NOT_UNIQUE"
};