export default {
    GET_CATEGORIES_SEND: "GET_CATEGORIES_SEND",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILED: "GET_CATEGORIES_FAILED",

    GET_NEW_MEM_SUCCESS: "GET_NEW_MEM_SUCCESS",
    GET_NEW_MEM_SEND: "GET_NEW_MEM_SEND",
    GET_NEW_MEM_FAILED: "GET_NEW_MEM_FAILED",

    POST_MEM_SUCCESS: "POST_MEM_SUCCESS",
    POST_MEM_SEND: "POST_MEM_SEND",
    POST_MEM_FAILED: "POST_MEM_FAILED",

    DISCARD_MEM_SEND: "DISCARD_MEM_SEND",
    DISCARD_MEM_SUCCESS: "DISCARD_MEM_SUCCESS",
    DISCARD_MEM_FAILED: "DISCARD_MEM_FAILED",

    LOGOUT: "LOGOUT",

    START_LOADING: "START_LOADING",
    FINISH_LOADING: "FINISH_LOADING",
};