export default {
    GET_CATEGORIES_SEND: "GET_CATEGORIES_SEND",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILED: "GET_CATEGORIES_FAILED",

    GET_NEW_MEM_SUCCESS: "GET_NEW_MEM_SUCCESS",
    GET_NEW_MEM_SEND: "GET_NEW_MEM_SEND",
    GET_NEW_MEM_FAILED: "GET_NEW_MEM_FAILED",

    POST_MEM_SUCCESS: "POST_MEM_SUCCESS",
    POST_MEM_SEND: "POST_MEM_SEND",
    POST_MEM_FAILED: "POST_MEM_FAILED",

    DISCARD_MEM_SEND: "DISCARD_MEM_SEND",
    DISCARD_MEM_SUCCESS: "DISCARD_MEM_SUCCESS",
    DISCARD_MEM_FAILED: "DISCARD_MEM_FAILED",

    LOGOUT: "LOGOUT",

    START_LOADING: "START_LOADING",
    FINISH_LOADING: "FINISH_LOADING",

    GET_USERINFO_SEND: "GET_USERINFO_SEND",
    GET_USERINFO_FAILED: "GET_USERINFO_FAILED",
    GET_USERINFO_SUCCESS: "GET_USERINFO_SUCCESS",

    BAN_USER_SEND:"BAN_USER_SEND",
    BAN_USER_FAILED:"BAN_USER_FAILED",
    BAN_USER_SUCCESS:"BAN_USER_SUCCESS",

    UNBAN_USER_SEND:"BAN_USER_SEND",
    UNBAN_USER_FAILED:"BAN_USER_FAILED",
    UNBAN_USER_SUCCESS:"BAN_USER_SUCCESS",

    GET_ALL_REPORTS_SEND: "GET_ALL_REPORTS_SEND",
    GET_ALL_REPORTS_FAILED: "GET_ALL_REPORTS_FAILED",
    GET_ALL_REPORTS_SUCCESS: "GET_ALL_REPORTS_SUCCESS",

    SET_REPORT_ERROR_READ: "SET_REPORT_ERROR_READ",

    SET_CURRENT_REPORTS_PAGE: "SET_CURRENT_REPORTS_PAGE",

};