module.exports = {
    INTERNAL_ERROR: "INTERNAL_ERROR",
    INCORRECT_DATA: "INCORRECT_DATA",
    NOT_REGISTERED: "NOT_REGISTERED",
    PASSWORDS_DONT_MATCH: "PASSWORDS_DONT_MATCH",
    EMAIL_NOT_UNIQUE: "EMAIL_NOT_UNIQUE",
    NO_SUCH_USER: "NO_SUCH_USER",
    NO_SUCH_IMAGE: "NO_SUCH_IMAGE",
    MEMES_ENDED: "MEMES_ENDED",
    NO_CATEGORIES: "NO_CATEGORIES",
    EMAIL_NOT_VALID: "EMAIL_NOT_VALID",
    USERNAME_NOT_VALID: "USERNAME_NOT_VALID",
    INCORRECT_BODY: "INCORRECT_BODY",
    NO_SUCH_MEM: "NO_SUCH_MEM",
    NO_SUCH_COMMENT: "NO_SUCH_COMMENT",
    REFERRAL_NOT_PRESENT: "REFERRAL_NOT_PRESENT"
};